version: '3'

services:
  sinatra-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/sinatra-db:/var/lib/postgresql/data
    networks:
      - sinatra_network

  sinatra-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - sinatra-db
    networks:
      - sinatra_network

networks:
  sinatra_network:
    driver: bridge