default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  host: sinatra-db
  port: 5432

development:
  <<: *default
  database: pokemon_development
  username: postgres
  password: password
